In [86]:
import pandas as pd

imdb = pd.read_csv(r"C:\Users\srija\OneDrive\Desktop\machine learning\DEEP LEARNING\datasets\IMDB Dataset.csv")

In [87]:
imdb.shape

(50000, 2)

In [88]:
imdb.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [89]:
imdb.isnull().sum()
imdb.drop_duplicates(inplace=True)

In [90]:
imdb.shape

(49582, 2)

## Text Pre-Processing

In [91]:
# 1. Convert to lowercase
# 2. Remove URLs (http, https)
# 3. Remove HTML
# 4. Remove Punctuations(.,?%#""#)
# 5. Remove stop-words (a, and, the .... etc)
# 6. Stemming and Limitization (Return basic forms)
# 7. Encode Target values (positve, negative, neutral)
# 8. Vectorizations (convert to numbers) -> TF-IDF

In [92]:
# Converting lowercases
imdb["review"] = imdb["review"].str.lower()

In [93]:
# Removing URLs
import re

# sample_text = "abc is the word, abc" => convert abc = xyz
# new_text = re.sub("abc", "xyx", sample_text)
# new_text = xyz is the word, xyz

def remove_urls(text):
    text = re.sub(r"http\S+" ," ", text) #(pattern, replace, string)
    return text

imdb["review"] = imdb["review"].apply(remove_urls)

In [94]:
# Removing Punctuations

def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]", "", text)
    return text

imdb["review"] = imdb["review"].apply(remove_punctuations)

In [95]:
# Removing HTML tags

def remove_htmlTags(text):
    text = re.sub(r"<.*?>", "", text)
    return text

imdb["review"] = imdb["review"].apply(remove_htmlTags)

In [96]:
# Remove stop-words

import nltk
nltk.download("punkt") # sentence tokenizer
nltk.download("punkt_tab") 
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\srija\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\srija\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\srija\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [97]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# sample_text = "I want to be rich"
# tokens = word_tokenize(sample_text)
# print(tokens)

In [98]:
# Stop Words
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word is stop_words:
            text.replace(word, "")

    return text

imdb["review"] = imdb["review"].apply(remove_stopwords)

In [99]:
imdb.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [100]:
# Stemming running -> run, played -> play
from nltk.stem import PorterStemmer

def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)
    
    return " ".join(stemmed_words)
imdb["review"] = imdb["review"].apply(stemming)

In [101]:
# Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

imdb["sentiment"] = le.fit_transform(imdb["sentiment"])

In [102]:
y = imdb["sentiment"]

In [ ]:
# Vectorizations -> convert the tokens into numericals for processing
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer() # max_featres=9000, I DIDNT DO IT MUST DO IT.

X = tf.fit_transform(imdb["review"])

In [110]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6560811 stored elements and shape (49582, 141948)>
  Coords	Values
  (0, 89906)	0.017480089399582698
  (0, 88990)	0.08207483915471349
  (0, 124822)	0.1797978415277287
  (0, 91034)	0.04916948249238846
  (0, 104563)	0.04124359118650199
  (0, 54957)	0.021363258654212517
  (0, 79097)	0.043811990337726536
  (0, 124733)	0.05397301868627194
  (0, 5511)	0.027748080739793346
  (0, 135898)	0.06753421093733333
  (0, 66865)	0.04171998958410708
  (0, 92118)	0.3717222685193974
  (0, 41298)	0.08837122337038748
  (0, 140994)	0.0454760598447118
  (0, 13711)	0.04912539587962667
  (0, 59652)	0.061597373828790804
  (0, 125305)	0.021026872879146515
  (0, 9744)	0.03552059282358378
  (0, 105050)	0.07096092465744601
  (0, 10367)	0.06457407847820054
  (0, 125323)	0.03676952097264709
  (0, 64314)	0.11146187929278768
  (0, 42443)	0.04812043498319506
  (0, 137277)	0.0429493047896598
  (0, 55997)	0.035424638970313026
  :	:
  (49581, 60435)	0.07637742670318899
  (49581, 129134)	0.08635242651242155
  (49581, 23350)	0.10038052937119671
  (49581, 108307)	0.09176210481068159
  (49581, 69060)	0.10395314399459779
  (49581, 131500)	0.09411179913808358
  (49581, 71422)	0.08758141157199317
  (49581, 63603)	0.13225400046909638
  (49581, 11569)	0.1046916226060487
  (49581, 56172)	0.11703196846837363
  (49581, 103812)	0.09938015202653429
  (49581, 62169)	0.15179226063366585
  (49581, 10183)	0.09912540976999867
  (49581, 128628)	0.14658611503524605
  (49581, 68643)	0.1684553046989847
  (49581, 117728)	0.18472745086641032
  (49581, 77979)	0.18146897911707155
  (49581, 30383)	0.14690558406952672
  (49581, 20725)	0.13552657588034694
  (49581, 86469)	0.15130462340587214
  (49581, 83603)	0.15964564859635974
  (49581, 23441)	0.11868887838746031
  (49581, 52795)	0.1449751982637297
  (49581, 103819)	0.1390825301058598
  (49581, 140918)	0.2672794422946269