In [103]:
import pandas as pd

imdb = pd.read_csv(r"C:\Users\srija\OneDrive\Desktop\machine learning\DEEP LEARNING\datasets\IMDB Dataset.csv")

In [104]:
imdb.shape

(50000, 2)

In [105]:
imdb.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [106]:
imdb.isnull().sum()
imdb.drop_duplicates(inplace=True)

In [107]:
imdb.shape

(49582, 2)

## Text Pre-Processing

In [108]:
# 1. Convert to lowercase
# 2. Remove URLs (http, https)
# 3. Remove HTML
# 4. Remove Punctuations(.,?%#""#)
# 5. Remove stop-words (a, and, the .... etc)
# 6. Stemming and Limitization (Return basic forms)
# 7. Encode Target values (positve, negative, neutral)
# 8. Vectorizations (convert to numbers) -> TF-IDF

In [109]:
# Converting lowercases
imdb["review"] = imdb["review"].str.lower()

In [110]:
# Removing URLs
import re

# sample_text = "abc is the word, abc" => convert abc = xyz
# new_text = re.sub("abc", "xyx", sample_text)
# new_text = xyz is the word, xyz

def remove_urls(text):
    text = re.sub(r"http\S+" ," ", text) #(pattern, replace, string)
    return text

imdb["review"] = imdb["review"].apply(remove_urls)

In [111]:
# Removing Punctuations

def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]", "", text)
    return text

imdb["review"] = imdb["review"].apply(remove_punctuations)

In [112]:
# Removing HTML tags

def remove_htmlTags(text):
    text = re.sub(r"<.*?>", "", text)
    return text

imdb["review"] = imdb["review"].apply(remove_htmlTags)

In [113]:
# Remove stop-words

import nltk
nltk.download("punkt") # sentence tokenizer
nltk.download("punkt_tab") 
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\srija\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\srija\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\srija\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [114]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# sample_text = "I want to be rich"
# tokens = word_tokenize(sample_text)
# print(tokens)

In [115]:
# Stop Words
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word is stop_words:
            text.replace(word, "")

    return text

imdb["review"] = imdb["review"].apply(remove_stopwords)

In [116]:
imdb.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [ ]:
# Stemming running -> run, played -> play
from nltk.stem import PorterStemmer

def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)
    
    return " ".join(stemmed_words)
imdb["review"] = imdb["review"].apply(stemming)

In [ ]:
# Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

imdb["sentiment"] = le.fit_transform(imdb["sentiment"])

In [ ]:
y = imdb["sentiment"]

In [ ]:
# Vectorizations -> convert the tokens into numericals for processing
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer() # max_featres=9000, I DIDNT DO IT MUST DO IT.

X = tf.fit_transform(imdb["review"])

In [ ]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5871114 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3122)	0.02032251735685024
  (0, 3097)	0.09542098470744526
  (0, 4440)	0.20903467205715237
  (0, 3151)	0.057164905655617715
  (0, 3688)	0.04795018941759714
  (0, 2023)	0.024837126680226217
  (0, 2809)	0.05093623457657249
  (0, 4438)	0.06274954229236089
  (0, 162)	0.032260181258981106
  (0, 4820)	0.07851591273828991
  (0, 2475)	0.04850405470299644
  (0, 3184)	0.43216782713328356
  (0, 1533)	0.10274122058172444
  (0, 4987)	0.05287089753313154
  (0, 442)	0.05711365014241208
  (0, 2178)	0.07161368973329611
  (0, 4455)	0.024446041394784856
  (0, 300)	0.041296577361905513
  (0, 3711)	0.08249984253761973
  (0, 323)	0.07507443472841555
  (0, 4460)	0.04274859304710011
  (0, 2386)	0.1295866356729789
  (0, 1581)	0.05594527309388424
  (0, 4864)	0.049933268194460693
  (0, 2051)	0.04118502050404425
  :	:
  (49581, 2285)	0.09370049477083149
  (49581, 1653)	0.16515065743591884
  (49581, 2206)	0.0807050171213464
  (49581, 4603)	0.09124520635183705
  (49581, 774)	0.10606814986101117
  (49581, 3827)	0.0969614002395767
  (49581, 2523)	0.10984319095358464
  (49581, 4659)	0.0994442296449171
  (49581, 2585)	0.09254382643575335
  (49581, 2353)	0.13974759078626203
  (49581, 378)	0.11062351220232874
  (49581, 2059)	0.12366306939993575
  (49581, 3639)	0.10501109054108233
  (49581, 2266)	0.1603929003910312
  (49581, 317)	0.10474191443679787
  (49581, 4584)	0.1548917714869443
  (49581, 2511)	0.17800008244249405
  (49581, 4160)	0.1951942180887046
  (49581, 1087)	0.15522934182669346
  (49581, 681)	0.1432055922664932
  (49581, 3024)	0.15987763334791602
  (49581, 2942)	0.16869126598604967
  (49581, 776)	0.12541386082039135
  (49581, 1955)	0.1531895792131522
  (49581, 3640)	0.14696302897312627

### Dataset and Data Loaders

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
print(f"X_train -> {X_train.shape}")
print(f"X_test -> {X_test.shape}")

X_train -> (39665, 5000)
X_test -> (9917, 5000)

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [ ]:
import numpy as np
X_train = X_train.toarray()
X_test = X_test.toarray()

In [ ]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [ ]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)

### Build RNN

In [ ]:
import torch.nn as nn
import torch.optim as optim

In [ ]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN LAYER
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True) #prebuilt RNN

        # FUlly ConneCted LayerR
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optional => shape(num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out,_ = self.rnn(x, h0) # 1st value -> hidden state of all the timesteps. (batch, seq_len, hidden_size)
                                # 2nd value -> final hidden state of last timesteps.
        
        out = self.fc(out[:, -1])
        return out

In [ ]:
input_size = X_train.shape[1]

model = RNN(input_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

### Training the Model

In [ ]:
# unsqueeze -> add 1 dimension, and squeeze reduce 1 dimension
epochs = 10
for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # Add singleton directions

        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batchsize, )

        loss = criterion(outputs, yb) # Computer Loss
        loss.backward() # back Prop
        optimizer.step() # weights update
    
    print(f"epoch = {epoch+1}/{epochs} & loss = {loss.item()}")

epoch = 1/10& loss = 0.19648171961307526
epoch = 2/10& loss = 0.2814295291900635
epoch = 3/10& loss = 0.23641245067119598
epoch = 4/10& loss = 0.09290947020053864
epoch = 5/10& loss = 0.19405098259449005
epoch = 6/10& loss = 0.34050822257995605
epoch = 7/10& loss = 0.09661438316106796
epoch = 8/10& loss = 0.19606171548366547
epoch = 9/10& loss = 0.24914251267910004
epoch = 10/10& loss = 0.27763280272483826

In [ ]:
# Evaluations
model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0

    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 87.40546536250882