In [1]:
import pandas as pd
import seaborn as sns

store = pd.read_csv("store.csv")
test = pd.read_csv("test.csv")
train = pd.read_csv("train.csv" ,low_memory=False)

In [2]:
print(train.shape, test.shape, store.shape)

(1017209, 9) (41088, 8) (1115, 10)

In [3]:
train = train.merge(store, on='Store', how='left')
test = test.merge(store, on='Store', how='left')

## 'train' dataset has been cleaned, pre processed, and encoded for model training.

In [4]:
train.isnull().sum()

Store                             0
DayOfWeek                         0
Date                              0
Sales                             0
Customers                         0
Open                              0
Promo                             0
StateHoliday                      0
SchoolHoliday                     0
StoreType                         0
Assortment                        0
CompetitionDistance            2642
CompetitionOpenSinceMonth    323348
CompetitionOpenSinceYear     323348
Promo2                            0
Promo2SinceWeek              508031
Promo2SinceYear              508031
PromoInterval                508031
dtype: int64

In [5]:
train['CompetitionDistance'] = train['CompetitionDistance'].fillna(train['CompetitionDistance'].median())

train = train.drop(columns=['PromoInterval'])

train['CompetitionOpenSinceMonth'] = train['CompetitionOpenSinceMonth'].fillna(0)

train['CompetitionOpenSinceYear'] = train['CompetitionOpenSinceYear'].fillna(0)

train['Promo2SinceWeek'] = train['Promo2SinceWeek'].fillna(0)

train['Promo2SinceYear'] = train['Promo2SinceYear'].fillna(0)

In [6]:
train.head(5)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,0.0,0.0
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,0.0,0.0
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,0.0,0.0

In [7]:
cols = ['StoreType', 'Assortment', 'StateHoliday']
train = pd.get_dummies(train, columns=cols, drop_first=True)

In [8]:
train['Date'] = pd.to_datetime(train['Date'])

for df in [train]:
    df['Year'] = df['Date'].dt.year
    df['Month'] = df['Date'].dt.month
    df['Week'] = df['Date'].dt.isocalendar().week

train.drop(columns=['Date'], inplace=True)

In [9]:
train.head(10)

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,...,StoreType_c,StoreType_d,Assortment_b,Assortment_c,StateHoliday_a,StateHoliday_b,StateHoliday_c,Year,Month,Week
0,1,5,5263,555,1,1,1,1270.0,9.0,2008.0,...,True,False,False,False,False,False,False,2015,7,31
1,2,5,6064,625,1,1,1,570.0,11.0,2007.0,...,False,False,False,False,False,False,False,2015,7,31
2,3,5,8314,821,1,1,1,14130.0,12.0,2006.0,...,False,False,False,False,False,False,False,2015,7,31
3,4,5,13995,1498,1,1,1,620.0,9.0,2009.0,...,True,False,False,True,False,False,False,2015,7,31
4,5,5,4822,559,1,1,1,29910.0,4.0,2015.0,...,False,False,False,False,False,False,False,2015,7,31
5,6,5,5651,589,1,1,1,310.0,12.0,2013.0,...,False,False,False,False,False,False,False,2015,7,31
6,7,5,15344,1414,1,1,1,24000.0,4.0,2013.0,...,False,False,False,True,False,False,False,2015,7,31
7,8,5,8492,833,1,1,1,7520.0,10.0,2014.0,...,False,False,False,False,False,False,False,2015,7,31
8,9,5,8565,687,1,1,1,2030.0,8.0,2000.0,...,False,False,False,True,False,False,False,2015,7,31
9,10,5,7185,681,1,1,1,3160.0,9.0,2009.0,...,False,False,False,False,False,False,False,2015,7,31

## 'test' data is going to be pre-processed, cleaned, and enncoded for future model running.

In [10]:
print(test.shape)
print(test.describe())
print(test.head(5))

(41088, 17)
                 Id         Store     DayOfWeek          Open         Promo  \
count  41088.000000  41088.000000  41088.000000  41077.000000  41088.000000
mean   20544.500000    555.899533      3.979167      0.854322      0.395833
std    11861.228267    320.274496      2.015481      0.352787      0.489035
min        1.000000      1.000000      1.000000      0.000000      0.000000
25%    10272.750000    279.750000      2.000000      1.000000      0.000000
50%    20544.500000    553.500000      4.000000      1.000000      0.000000
75%    30816.250000    832.250000      6.000000      1.000000      1.000000
max    41088.000000   1115.000000      7.000000      1.000000      1.000000

       SchoolHoliday  CompetitionDistance  CompetitionOpenSinceMonth  \
count   41088.000000         40992.000000               25872.000000
mean        0.443487          5088.583138                   7.035250
std         0.496802          7225.487467                   3.143015
min         0.000000            20.000000                   1.000000
25%         0.000000           720.000000                   4.000000
50%         0.000000          2425.000000                   7.000000
75%         1.000000          6480.000000                   9.000000
max         1.000000         75860.000000                  12.000000

       CompetitionOpenSinceYear        Promo2  Promo2SinceWeek  \
count              25872.000000  41088.000000     23856.000000
mean                2008.641929      0.580607        24.426559
std                    6.862400      0.493466        14.161312
min                 1900.000000      0.000000         1.000000
25%                 2006.000000      0.000000        13.000000
50%                 2010.000000      1.000000        22.000000
75%                 2012.000000      1.000000        37.000000
max                 2015.000000      1.000000        49.000000

       Promo2SinceYear
count     23856.000000
mean       2011.820926
std           1.692166
min        2009.000000
25%        2011.000000
50%        2012.000000
75%        2013.000000
max        2015.000000
   Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday  \
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0

  StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0         c          a               1270.0                        9.0
1         a          a              14130.0                       12.0
2         a          c              24000.0                        4.0
3         a          a               7520.0                       10.0
4         a          c               2030.0                        8.0

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN
1                    2006.0       1             14.0           2011.0
2                    2013.0       0              NaN              NaN
3                    2014.0       0              NaN              NaN
4                    2000.0       0              NaN              NaN

     PromoInterval
0              NaN
1  Jan,Apr,Jul,Oct
2              NaN
3              NaN
4              NaN

In [11]:
test['CompetitionDistance'] = pd.to_numeric(test['CompetitionDistance'], errors='coerce')
median_distance = train['CompetitionDistance'].median()

In [12]:
test['Open'] = test['Open'].fillna(1)

test['CompetitionDistance'] = test['CompetitionDistance'].fillna(median_distance)

test['CompetitionOpenSinceMonth'] = test['CompetitionOpenSinceMonth'].fillna(0)

test['CompetitionOpenSinceYear'] = test['CompetitionOpenSinceYear'].fillna(0)

test['Promo2SinceWeek'] = test['Promo2SinceWeek'].fillna(0)

test['Promo2SinceYear'] = test['Promo2SinceYear'].fillna(0)

test.drop(columns=['PromoInterval'], inplace=True)

train = train.drop(columns=['Customers'])

In [13]:
print(test['StateHoliday'].unique(), test['StoreType'].unique(), test['Assortment'].unique())

['0' 'a'] ['c' 'a' 'd' 'b'] ['a' 'c' 'b']

In [14]:
cols = ['StateHoliday', 'StoreType', 'Assortment']
test = pd.get_dummies(test, columns=cols, drop_first=True)

In [15]:
test['Date'] = pd.to_datetime(test['Date'])

for df in [test]:
    df['Year'] = df['Date'].dt.year
    df['Month'] = df['Date'].dt.month
    df['Week'] = df['Date'].dt.isocalendar().week

test.drop(columns=['Date'], inplace=True)

In [16]:
test.head(10)

,Id,Store,DayOfWeek,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,...,Promo2SinceYear,StateHoliday_a,StoreType_b,StoreType_c,StoreType_d,Assortment_b,Assortment_c,Year,Month,Week
0,1,1,4,1.0,1,0,1270.0,9.0,2008.0,0,...,0.0,False,False,True,False,False,False,2015,9,38
1,2,3,4,1.0,1,0,14130.0,12.0,2006.0,1,...,2011.0,False,False,False,False,False,False,2015,9,38
2,3,7,4,1.0,1,0,24000.0,4.0,2013.0,0,...,0.0,False,False,False,False,False,True,2015,9,38
3,4,8,4,1.0,1,0,7520.0,10.0,2014.0,0,...,0.0,False,False,False,False,False,False,2015,9,38
4,5,9,4,1.0,1,0,2030.0,8.0,2000.0,0,...,0.0,False,False,False,False,False,True,2015,9,38
5,6,10,4,1.0,1,0,3160.0,9.0,2009.0,0,...,0.0,False,False,False,False,False,False,2015,9,38
6,7,11,4,1.0,1,0,960.0,11.0,2011.0,1,...,2012.0,False,False,False,False,False,True,2015,9,38
7,8,12,4,1.0,1,0,1070.0,0.0,0.0,1,...,2010.0,False,False,False,False,False,True,2015,9,38
8,9,13,4,1.0,1,0,310.0,0.0,0.0,1,...,2009.0,False,False,False,True,False,False,2015,9,38
9,10,14,4,1.0,1,0,1300.0,3.0,2014.0,1,...,2011.0,False,False,False,False,False,False,2015,9,38

In [17]:
test.dtypes

Id                             int64
Store                          int64
DayOfWeek                      int64
Open                         float64
Promo                          int64
SchoolHoliday                  int64
CompetitionDistance          float64
CompetitionOpenSinceMonth    float64
CompetitionOpenSinceYear     float64
Promo2                         int64
Promo2SinceWeek              float64
Promo2SinceYear              float64
StateHoliday_a                  bool
StoreType_b                     bool
StoreType_c                     bool
StoreType_d                     bool
Assortment_b                    bool
Assortment_c                    bool
Year                           int32
Month                          int32
Week                          UInt32
dtype: object

##  Using "Train" dataset to do Linear Regression model.

In [18]:
from sklearn.model_selection import train_test_split 
X  = train.drop(columns=['Sales'])
Y = train['Sales']

X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y, test_size=0.20, random_state=42
)

In [19]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [20]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

Y_pred = model.predict(X_test)

print("R2 Score:", r2_score(Y_test, Y_pred)*100)
print("MAE:", mean_absolute_error(Y_test, Y_pred))
print("RMSE", np.sqrt(mean_squared_error(Y_test, Y_pred)))
print(mean_absolute_percentage_error(Y_test,Y_pred))

R2 Score: 57.077711162903654
MAE: 1756.4751539458439
RMSE 2519.4622061936566
4.137235580723232e+17

In [21]:
# Evalutate 
from sklearn.metrics import r2_score
r2 = r2_score(Y_test, Y_pred)
print("r-squared: ",r2*100,"%")

n = X_test.shape[0]
p = X_test.shape[1]

adjusted_r2 = 1 - ((1-r2) * (n-1)/n-p-1)
print("adjusted r^2 value: ", adjusted_r2)

r-squared:  57.077711162903654 %
adjusted r^2 value:  23.57077922143374

In [22]:
X = train.drop(columns=['Sales'])
y = train['Sales']

In [23]:
model.fit(X, y)

LinearRegression()

In [24]:
X_test_final = test.reindex(columns=X.columns, fill_value=0)

In [25]:
predictions = model.predict(X_test_final)